replicaCount: 1
image:
  repository: kirankumatkar217/sample-app
  tag: "v4.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

configmap:
  APP_VERSION: "v1.0.0"
  ENVIRONMENT: "staging"

probes:
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 15