apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Release.Namespace }}
data:
  APP_VERSION: {{ .Values.configmap.APP_VERSION | quote }}
  ENVIRONMENT: {{ .Values.configmap.ENVIRONMENT | quote }}