apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: sample-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}