apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops-project
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: "GitOps lab project"

  sourceRepos:
    - "*"       # Allow any repo for now

  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"    # Allow any namespace for now

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"         # Allow all cluster-scoped resources

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"         # Allow all namespace-scoped resources