# gitops-config/apps/monitoring-extras-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-extras
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"   # Sync AFTER kube-prometheus-stack (wave 0)
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://github.com/kiran-kumatkar/k8s-monitoring
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true