apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-staging
  namespace: argocd
spec:
  project: gitops-project
  source:
    repoURL: https://github.com/kiran-kumatkar/gitops-config
    targetRevision: HEAD
    path: helm/sample-app
    helm:
      valueFiles:
        - ../../environments/staging/values.yaml
      parameters:
        - name: image.tag
          value: "v1.0.0"              
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true